FIRST LDA #5
	  STA  INDEX
	  LDB  #INDEX
	  BASE INDEX
	  +JSUB ROOT
CLOOP +LDX  ZERO
	  LDA  EOF
	  ADD SCORE,X
	  STA TEMP,X
EOF   WORD  8
SCORE WORD 1
TEMP RESB 1
	STA  @GAMMA
	+JSUB ROOT
GAMMA RESW 1
INDEX RESW 1
BETA RESB 4096
ZERO WORD 0
ALPHA WORD 4096
ROOT LDX ZERO
	 LDX ALPHA
	 TD OUTPUT
	 JEQ ROOT
	 STCH BETA,X
	 WD OUTPUT
	 TIXR S
	 JLT ROOT
	 RSUB
INPUT BYTE X'454F'
OUTPUT BYTE X'05'
	   END FIRST